server:
  port: 10030
  shutdown: graceful
  servlet:
    context-path: /api/v1

spring:
  application:
    name: pet-project-1
  data:
    mongodb:
      uri: mongodb://localhost:27017/pet-project-1

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
